package orar.dlfragment;

public enum DLConstructor {
	NOMINAL, CONJUNCTION, Horn_DISJUNCTION, NonHorn_DISJUNCTION, NonHorn_NEGATION, FUNCTIONALITY, MAX_CARDINALITY, MIN_CARDINALITY, EXISTENTIAL_RESTRICTION, UNIVERSAL_RESTRICTION, NonHorn_UNIVERSAL_RESTRICTION, DATATYPE, TRANSITIVITY, ROLECHAIN, HASVALUE, REFLEXSIVEROLE;
}
